### ISSUE TITLE
Ajuster le thème

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/blog#9]
## TODO 
- [x] Créer des badges pour les tags
- [x] Définir le thème graphique
- [x] Ajuster la taille de la grid
- [x] Retirer le theme dark
